name: "Remove Stale Branches"
description: "Cleanup stale branches from a repository"
author: "Francois Picalausa"
runs:
  using: "node16"
  main: "dist/index.js"
inputs:
  github-token:
    description: "PAT for GitHub API authentication."
    required: false
    default: ${{ github.token }}
  dry-run:
    description: "Flag that prevents this action from doing any modification to the repository."
    required: false
    default: "false"
  package-name:
    description: "Name of the package to remove"
    required: true
  protect-latest-n-versions:
    description: "Regardless of the package age, always keep the latest N versions"
    default: "2"
    required: false
  days-before-package-is-old:
    description: "Number of days before a package is considered old enough to be removed."
    default: "90"
    required: false
  operations-per-run:
    description: "Maximum number of stale branches to look at in any run of this action."
    default: "10"
    required: false
